[project]
name = "yt-stream-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "playwright>=1.53.0",
    "youtube-transcript-api>=1.1.1",
]
